spring:
  main:
    web-application-type: none

loader:
  backend:
    base-url: http://localhost:8080
    hire-path: /employees/hire

  defaults:
    rule-system-code: ESP
    employee-type-code: EMP

  generation:
    count: 10
    seed: 12345
